// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OvertimeSystem.API.Data;

#nullable disable

namespace OvertimeSystem.API.Migrations
{
    [DbContext(typeof(OvertimeDbContext))]
    [Migration("20251124170435_ChangesOne")]
    partial class ChangesOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<short?>("Otp")
                        .HasColumnType("smallint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("AccountId", "RoleId")
                        .IsUnique();

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.ApprovedOvertime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CalculatedCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte[]>("Document")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("RateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("TotalHours")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("RateId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("ApprovedOvertime");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("Nik")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BudgetMonth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("HoursConsumed")
                        .HasColumnType("smallint");

                    b.Property<short>("InitialHours")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "BudgetMonth")
                        .IsUnique();

                    b.ToTable("OvertimeBudgets");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short>("MaxDailyHours")
                        .HasColumnType("smallint");

                    b.Property<short>("MaxWeeklyHours")
                        .HasColumnType("smallint");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("WeekdayStartTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WeekendEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WeekendStartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("OvertimePolicies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            MaxDailyHours = (short)4,
                            MaxWeeklyHours = (short)18,
                            PolicyName = "Standard Labor Law Compliance",
                            WeekdayStartTime = new TimeSpan(0, 19, 0, 0, 0),
                            WeekendEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            WeekendStartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaseDivisor")
                        .HasColumnType("int");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("HourOrder")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("RateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OvertimeRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eea400e3-05fc-4953-a03b-dea2e5ae6c9d"),
                            BaseDivisor = 173,
                            DayType = "NORMAL",
                            HourOrder = (short)1,
                            Multiplier = 1.5m,
                            RateName = "WD 1st Hr"
                        },
                        new
                        {
                            Id = new Guid("729428f5-e145-4c94-8197-cd826c141b19"),
                            BaseDivisor = 173,
                            DayType = "NORMAL",
                            HourOrder = (short)2,
                            Multiplier = 2.0m,
                            RateName = "WD 2nd+ Hr"
                        },
                        new
                        {
                            Id = new Guid("cc4b5dc1-4897-4e63-8b90-42226d99e665"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)1,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 1"
                        },
                        new
                        {
                            Id = new Guid("88c79f2f-5f46-49e8-b129-e0b2bac2f51c"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)2,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 2"
                        },
                        new
                        {
                            Id = new Guid("fcb1ee97-dda1-49f1-a2be-ac62379ebc62"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)3,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 3"
                        },
                        new
                        {
                            Id = new Guid("1e6de3d8-4397-4bd9-a634-ea23705f0346"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)4,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 4"
                        },
                        new
                        {
                            Id = new Guid("a1b0ab22-346a-4999-b281-c7967c4e2a0a"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)5,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 5"
                        },
                        new
                        {
                            Id = new Guid("b4a2eb51-fc02-4693-ae92-91c1e213a9e9"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)6,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 6"
                        },
                        new
                        {
                            Id = new Guid("241770ff-7e65-4421-a89a-447c1cfb825c"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)7,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 7"
                        },
                        new
                        {
                            Id = new Guid("327e8bfa-d4c5-414d-b87d-efa1be51d788"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)8,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 8"
                        },
                        new
                        {
                            Id = new Guid("b8d5cec1-1322-4778-9f86-f82d58b9b94d"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)9,
                            Multiplier = 3.0m,
                            RateName = "WH Hr 9"
                        },
                        new
                        {
                            Id = new Guid("f2e301bd-7dc6-4ad2-84a7-77d98ce327bd"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)10,
                            Multiplier = 4.0m,
                            RateName = "WH Hr 10"
                        },
                        new
                        {
                            Id = new Guid("8009ba9a-9546-45d9-b70d-ee518b6f1935"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)11,
                            Multiplier = 4.0m,
                            RateName = "WH Hr 11"
                        },
                        new
                        {
                            Id = new Guid("01e1e8bb-d295-47e8-9bcf-4901194ab389"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)12,
                            Multiplier = 4.0m,
                            RateName = "WH Hr 12"
                        });
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("RequestedHours")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PolicyId");

                    b.ToTable("OvertimeRequests");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Employee"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("OvertimeSystem.API.Models.Account", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.AccountRole", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.ApprovedOvertime", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.OvertimeRate", "Rate")
                        .WithMany("ApprovedOvertimeRecords")
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.OvertimeRequest", "Request")
                        .WithOne("ApprovedOvertime")
                        .HasForeignKey("OvertimeSystem.API.Models.ApprovedOvertime", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rate");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeBudget", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithMany("OvertimeBudgets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.OvertimePolicy", "Policy")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("OvertimeBudgets");

                    b.Navigation("OvertimeRequests");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimePolicy", b =>
                {
                    b.Navigation("OvertimeRequests");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRate", b =>
                {
                    b.Navigation("ApprovedOvertimeRecords");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.Navigation("ApprovedOvertime")
                        .IsRequired();
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
