// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OvertimeSystem.API.Data;

#nullable disable

namespace OvertimeSystem.API.Migrations
{
    [DbContext(typeof(OvertimeDbContext))]
    [Migration("20251124162307_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<short?>("Otp")
                        .HasColumnType("smallint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("AccountId", "RoleId")
                        .IsUnique();

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.ApprovedOvertime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CalculatedCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte[]>("Document")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("RateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("TotalHours")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("RateId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("ApprovedOvertime");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("Nik")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BudgetMonth")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("HoursConsumed")
                        .HasColumnType("smallint");

                    b.Property<short>("InitialHours")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "BudgetMonth")
                        .IsUnique();

                    b.ToTable("OvertimeBudgets");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short>("MaxDailyHours")
                        .HasColumnType("smallint");

                    b.Property<short>("MaxWeeklyHours")
                        .HasColumnType("smallint");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("WeekdayStartTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WeekendEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WeekendStartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("OvertimePolicies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            MaxDailyHours = (short)4,
                            MaxWeeklyHours = (short)18,
                            PolicyName = "Standard Labor Law Compliance",
                            WeekdayStartTime = new TimeSpan(0, 19, 0, 0, 0),
                            WeekendEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            WeekendStartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaseDivisor")
                        .HasColumnType("int");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("HourOrder")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("RateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OvertimeRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abf99de4-240d-4ea0-a044-1296386bde37"),
                            BaseDivisor = 173,
                            DayType = "NORMAL",
                            HourOrder = (short)1,
                            Multiplier = 1.5m,
                            RateName = "WD 1st Hr"
                        },
                        new
                        {
                            Id = new Guid("43860f9a-9c7c-4dce-95bc-a7da51161e12"),
                            BaseDivisor = 173,
                            DayType = "NORMAL",
                            HourOrder = (short)2,
                            Multiplier = 2.0m,
                            RateName = "WD 2nd+ Hr"
                        },
                        new
                        {
                            Id = new Guid("bc759a71-b3a7-4549-82d0-ee5ea9f863b9"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)1,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 1"
                        },
                        new
                        {
                            Id = new Guid("76ec3585-044f-4b72-ad4b-d1f51e784314"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)2,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 2"
                        },
                        new
                        {
                            Id = new Guid("21b52e6b-f31c-4c00-b4e9-8249340f8149"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)3,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 3"
                        },
                        new
                        {
                            Id = new Guid("ba5071e3-fbf0-440e-a238-66c0811ac6de"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)4,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 4"
                        },
                        new
                        {
                            Id = new Guid("abfa5f7e-ce1b-4421-bbf5-828be729cdc1"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)5,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 5"
                        },
                        new
                        {
                            Id = new Guid("a270a553-d92f-43ea-8e8b-d9253625abac"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)6,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 6"
                        },
                        new
                        {
                            Id = new Guid("623cf23a-0ea4-4912-b42e-446928912b2d"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)7,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 7"
                        },
                        new
                        {
                            Id = new Guid("16c6d00d-7410-4b71-b29c-c906a0ee9ace"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)8,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 8"
                        },
                        new
                        {
                            Id = new Guid("10472b87-d994-4b63-845c-22386efde689"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)9,
                            Multiplier = 3.0m,
                            RateName = "WH Hr 9"
                        },
                        new
                        {
                            Id = new Guid("06d0d3b0-9664-4007-b156-cc9e44d3de3a"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)10,
                            Multiplier = 4.0m,
                            RateName = "WH Hr 10"
                        },
                        new
                        {
                            Id = new Guid("114e0833-ac28-49fa-b0af-acdcd6b2bb1f"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)11,
                            Multiplier = 4.0m,
                            RateName = "WH Hr 11"
                        },
                        new
                        {
                            Id = new Guid("8f5124c6-88dc-4ccd-846a-17667ccf0367"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = (short)12,
                            Multiplier = 4.0m,
                            RateName = "WH Hr 12"
                        });
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("RequestedHours")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PolicyId");

                    b.ToTable("OvertimeRequests");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Employee"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("OvertimeSystem.API.Models.Account", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.AccountRole", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.ApprovedOvertime", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.OvertimeRate", "Rate")
                        .WithMany("ApprovedOvertimeRecords")
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.OvertimeRequest", "Request")
                        .WithOne("ApprovedOvertime")
                        .HasForeignKey("OvertimeSystem.API.Models.ApprovedOvertime", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rate");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeBudget", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithMany("OvertimeBudgets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.OvertimePolicy", "Policy")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("OvertimeBudgets");

                    b.Navigation("OvertimeRequests");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimePolicy", b =>
                {
                    b.Navigation("OvertimeRequests");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRate", b =>
                {
                    b.Navigation("ApprovedOvertimeRecords");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.Navigation("ApprovedOvertime")
                        .IsRequired();
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
