// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OvertimeSystem.API.Data;

#nullable disable

namespace OvertimeSystem.API.Migrations
{
    [DbContext(typeof(OvertimeSystemDbContext))]
    [Migration("20251125062442_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<long?>("Otp")
                        .HasColumnType("bigint")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.HasKey("EmployeeId");

                    b.ToTable("tbl_account", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "RoleId")
                        .IsUnique();

                    b.ToTable("tbl_account_role", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.ApprovedOvertime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("CalculatedCost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("calculated_cost");

                    b.Property<Guid>("RateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rate_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<short>("TotalHours")
                        .HasColumnType("smallint")
                        .HasColumnName("total_hours");

                    b.HasKey("Id");

                    b.ToTable("tbl_approved_overtime", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manager_id");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("salary");

                    b.HasKey("Id");

                    b.HasIndex("Nik")
                        .IsUnique();

                    b.ToTable("tbl_employee", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("BudgetMonth")
                        .HasColumnType("datetime2")
                        .HasColumnName("budget_month");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<short>("HoursConsumed")
                        .HasColumnType("smallint")
                        .HasColumnName("hours_consumed");

                    b.Property<short>("InitialHours")
                        .HasColumnType("smallint")
                        .HasColumnName("initial_hours");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "BudgetMonth")
                        .IsUnique();

                    b.ToTable("tbl_overtime_budget", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxDailyHours")
                        .HasColumnType("int")
                        .HasColumnName("max_daily_hours");

                    b.Property<int>("MaxWeeklyHours")
                        .HasColumnType("int")
                        .HasColumnName("max_weekly_hours");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("policy_name");

                    b.Property<TimeSpan>("WeekdayStartTime")
                        .HasColumnType("time")
                        .HasColumnName("weekday_start_time");

                    b.Property<TimeSpan>("WeekendEndTime")
                        .HasColumnType("time")
                        .HasColumnName("weekend_end_time");

                    b.Property<TimeSpan>("WeekendStartTime")
                        .HasColumnType("time")
                        .HasColumnName("weekend_start_time");

                    b.HasKey("Id");

                    b.ToTable("tbl_overtime_policy", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("BaseDivisor")
                        .HasColumnType("int")
                        .HasColumnName("base_divisor");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("day_type");

                    b.Property<int>("HourOrder")
                        .HasColumnType("int")
                        .HasColumnName("hour_order");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("multiplier");

                    b.Property<string>("RateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rate_name");

                    b.HasKey("Id");

                    b.ToTable("tbl_overtime_rate", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("policy_id");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("request_type");

                    b.Property<short>("RequestedHours")
                        .HasColumnType("smallint")
                        .HasColumnName("requested_hours");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("tbl_overtime_request", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tbl_role", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
