// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OvertimeSystem.API.Data;

#nullable disable

namespace OvertimeSystem.API.Migrations
{
    [DbContext(typeof(OvertimeSystemDbContext))]
    [Migration("20251126023824_AddRelationsAndCardinality")]
    partial class AddRelationsAndCardinality
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<long?>("Otp")
                        .HasColumnType("bigint")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.HasKey("EmployeeId");

                    b.ToTable("tbl_account", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("AccountId", "RoleId")
                        .IsUnique();

                    b.ToTable("tbl_account_role", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.ApprovedOvertime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("CalculatedCost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("calculated_cost");

                    b.Property<Guid>("RateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rate_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<short>("TotalHours")
                        .HasColumnType("smallint")
                        .HasColumnName("total_hours");

                    b.HasKey("Id");

                    b.HasIndex("RateId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("tbl_approved_overtime", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gender");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manager_id");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("nik");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("salary");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("Nik")
                        .IsUnique();

                    b.ToTable("tbl_employee", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("BudgetMonth")
                        .HasColumnType("datetime2")
                        .HasColumnName("budget_month");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<int>("HoursConsumed")
                        .HasColumnType("int")
                        .HasColumnName("hours_consumed");

                    b.Property<int>("InitialHours")
                        .HasColumnType("int")
                        .HasColumnName("initial_hours");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "BudgetMonth")
                        .IsUnique();

                    b.ToTable("tbl_overtime_budget", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxDailyHours")
                        .HasColumnType("int")
                        .HasColumnName("max_daily_hours");

                    b.Property<int>("MaxWeeklyHours")
                        .HasColumnType("int")
                        .HasColumnName("max_weekly_hours");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("policy_name");

                    b.Property<TimeSpan>("WeekdayStartTime")
                        .HasColumnType("time")
                        .HasColumnName("weekday_start_time");

                    b.Property<TimeSpan>("WeekendEndTime")
                        .HasColumnType("time")
                        .HasColumnName("weekend_end_time");

                    b.Property<TimeSpan>("WeekendStartTime")
                        .HasColumnType("time")
                        .HasColumnName("weekend_start_time");

                    b.HasKey("Id");

                    b.ToTable("tbl_overtime_policy", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("BaseDivisor")
                        .HasColumnType("int")
                        .HasColumnName("base_divisor");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("day_type");

                    b.Property<int>("HourOrder")
                        .HasColumnType("int")
                        .HasColumnName("hour_order");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("multiplier");

                    b.Property<string>("RateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rate_name");

                    b.HasKey("Id");

                    b.ToTable("tbl_overtime_rate", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("policy_id");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("request_type");

                    b.Property<short>("RequestedHours")
                        .HasColumnType("smallint")
                        .HasColumnName("requested_hours");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PolicyId");

                    b.ToTable("tbl_overtime_request", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tbl_role", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("OvertimeSystem.API.Models.Account", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.AccountRole", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.ApprovedOvertime", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.OvertimeRate", "Rate")
                        .WithMany("ApprovedOvertimes")
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.OvertimeRequest", "Request")
                        .WithOne("ApprovedOvertime")
                        .HasForeignKey("OvertimeSystem.API.Models.ApprovedOvertime", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rate");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Manager")
                        .WithMany("Employees")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeBudget", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithMany("OvertimeBudgets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.OvertimePolicy", "Policy")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Employees");

                    b.Navigation("OvertimeBudgets");

                    b.Navigation("OvertimeRequests");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimePolicy", b =>
                {
                    b.Navigation("OvertimeRequests");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRate", b =>
                {
                    b.Navigation("ApprovedOvertimes");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.Navigation("ApprovedOvertime");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
