// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OvertimeSystem.API.Data;

#nullable disable

namespace OvertimeSystem.API.Migrations
{
    [DbContext(typeof(OvertimeSystemDbContext))]
    partial class OvertimeSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<long?>("Otp")
                        .HasColumnType("bigint")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.HasKey("EmployeeId");

                    b.ToTable("tbl_account", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("AccountId", "RoleId")
                        .IsUnique();

                    b.ToTable("tbl_account_role", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.ApprovedOvertime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("CalculatedCost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("calculated_cost");

                    b.Property<Guid>("RateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rate_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<short>("TotalHours")
                        .HasColumnType("smallint")
                        .HasColumnName("total_hours");

                    b.HasKey("Id");

                    b.HasIndex("RateId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("tbl_approved_overtime", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gender");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manager_id");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("nik");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("position");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("salary");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("Nik")
                        .IsUnique();

                    b.ToTable("tbl_employee", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("BudgetMonth")
                        .HasColumnType("datetime2")
                        .HasColumnName("budget_month");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<int>("HoursConsumed")
                        .HasColumnType("int")
                        .HasColumnName("hours_consumed");

                    b.Property<int>("InitialHours")
                        .HasColumnType("int")
                        .HasColumnName("initial_hours");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "BudgetMonth")
                        .IsUnique();

                    b.ToTable("tbl_overtime_budget", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxDailyHours")
                        .HasColumnType("int")
                        .HasColumnName("max_daily_hours");

                    b.Property<int>("MaxWeeklyHours")
                        .HasColumnType("int")
                        .HasColumnName("max_weekly_hours");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("policy_name");

                    b.Property<TimeSpan>("WeekdayStartTime")
                        .HasColumnType("time")
                        .HasColumnName("weekday_start_time");

                    b.Property<TimeSpan>("WeekendEndTime")
                        .HasColumnType("time")
                        .HasColumnName("weekend_end_time");

                    b.Property<TimeSpan>("WeekendStartTime")
                        .HasColumnType("time")
                        .HasColumnName("weekend_start_time");

                    b.HasKey("Id");

                    b.ToTable("tbl_overtime_policy", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            MaxDailyHours = 4,
                            MaxWeeklyHours = 18,
                            PolicyName = "Standard",
                            WeekdayStartTime = new TimeSpan(0, 19, 0, 0, 0),
                            WeekendEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            WeekendStartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("BaseDivisor")
                        .HasColumnType("int")
                        .HasColumnName("base_divisor");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("day_type");

                    b.Property<int>("HourOrder")
                        .HasColumnType("int")
                        .HasColumnName("hour_order");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("multiplier");

                    b.Property<string>("RateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rate_name");

                    b.HasKey("Id");

                    b.ToTable("tbl_overtime_rate", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a68ab98b-04a1-4328-8bc2-1dee00cef5fc"),
                            BaseDivisor = 173,
                            DayType = "NORMAL",
                            HourOrder = 1,
                            Multiplier = 1.5m,
                            RateName = "WD 1st Hr"
                        },
                        new
                        {
                            Id = new Guid("a2b7ab11-ac75-4697-a1b6-688273e33f45"),
                            BaseDivisor = 173,
                            DayType = "NORMAL",
                            HourOrder = 2,
                            Multiplier = 2.0m,
                            RateName = "WD 2nd+ Hr"
                        },
                        new
                        {
                            Id = new Guid("3e755ce3-f7a1-44b8-8fb3-dd4e79f32080"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 1,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 1"
                        },
                        new
                        {
                            Id = new Guid("2f4df0c8-b0fc-4262-9021-dcd72370e1e2"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 2,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 2"
                        },
                        new
                        {
                            Id = new Guid("6d8a23d2-b479-4869-9fa6-608b91d93534"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 3,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 3"
                        },
                        new
                        {
                            Id = new Guid("520112fd-9460-46ed-b5fb-ae36385e197e"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 4,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 4"
                        },
                        new
                        {
                            Id = new Guid("c5e12625-cd58-44b6-bc2d-885078dab00e"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 5,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 5"
                        },
                        new
                        {
                            Id = new Guid("42341d1c-6fec-4a2e-b91a-7cba3404a14b"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 6,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 6"
                        },
                        new
                        {
                            Id = new Guid("5ef2a883-d36a-4780-af9b-97892fb90409"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 7,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 7"
                        },
                        new
                        {
                            Id = new Guid("47965aa1-5ab5-46f9-9d0f-2c346fa5e140"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 8,
                            Multiplier = 2.0m,
                            RateName = "WH Hr 8"
                        },
                        new
                        {
                            Id = new Guid("dc7faf56-8c64-4786-a9ee-6d5988023c33"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 9,
                            Multiplier = 3.0m,
                            RateName = "WD Hr 9"
                        },
                        new
                        {
                            Id = new Guid("06c93357-eddf-48ee-90c9-448ee1508289"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 10,
                            Multiplier = 4.0m,
                            RateName = "WH Hr 10"
                        },
                        new
                        {
                            Id = new Guid("d34bbe1a-27eb-4ff8-be02-b1a1f2d9383d"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 11,
                            Multiplier = 4.0m,
                            RateName = "WH Hr 11"
                        },
                        new
                        {
                            Id = new Guid("890a8818-d874-42e7-8c6c-3ef341dbe5bd"),
                            BaseDivisor = 173,
                            DayType = "WEEKEND_HOLIDAY",
                            HourOrder = 12,
                            Multiplier = 4.0m,
                            RateName = "WH Hr 12"
                        });
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("employee_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("policy_id");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("request_type");

                    b.Property<short>("RequestedHours")
                        .HasColumnType("smallint")
                        .HasColumnName("requested_hours");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PolicyId");

                    b.ToTable("tbl_overtime_request", (string)null);
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tbl_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Employee"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("OvertimeSystem.API.Models.Account", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.AccountRole", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.ApprovedOvertime", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.OvertimeRate", "Rate")
                        .WithMany("ApprovedOvertimes")
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.OvertimeRequest", "Request")
                        .WithOne("ApprovedOvertime")
                        .HasForeignKey("OvertimeSystem.API.Models.ApprovedOvertime", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rate");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Manager")
                        .WithMany("Employees")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeBudget", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithMany("OvertimeBudgets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.HasOne("OvertimeSystem.API.Models.Employee", "Employee")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OvertimeSystem.API.Models.OvertimePolicy", "Policy")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Account", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Employee", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Employees");

                    b.Navigation("OvertimeBudgets");

                    b.Navigation("OvertimeRequests");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimePolicy", b =>
                {
                    b.Navigation("OvertimeRequests");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRate", b =>
                {
                    b.Navigation("ApprovedOvertimes");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.OvertimeRequest", b =>
                {
                    b.Navigation("ApprovedOvertime");
                });

            modelBuilder.Entity("OvertimeSystem.API.Models.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
